language: node_js

node_js: '10'

env:
  global:
    - FORCE_COLOR=1

cache:
  directories:
    - ~/.npm

script:
  - npm run prettier
  - npm run tslint
  - npm run build
  - npm test
  - ./node_modules/.bin/nyc report --reporter json
  - bash <(curl -s https://codecov.io/bash)

deploy:
  skip_cleanup: true
  provider: script
  script: ./node_modules/.bin/semantic-release
  on:
    branch: master
